---
- name: test if httpd_servername is set correctly
  assert:
    that:
      - httpd_servername is defined
    quiet: yes

- name: test if httpd_port is set correctly
  assert:
    that:
      - httpd_port is defined
      - httpd_port is number
      - httpd_port | int > 0
      - httpd_port | int < 65536
    quiet: yes

- name: test if httpd_ssl_servername is set correctly
  assert:
    that:
      - httpd_ssl_servername is defined
    quiet: yes

- name: test if httpd_ssl_port is set correctly
  assert:
    that:
      - httpd_ssl_port is defined
      - httpd_ssl_port is number
      - httpd_ssl_port | int > 0
      - httpd_ssl_port | int < 65535
      - httpd_ssl_port != httpd_port
    quiet: yes

- name: test if httpd_proxy_preserve_host is set correctly
  assert:
    that:
      - httpd_proxy_preserve_host is defined
      - httpd_proxy_preserve_host is boolean
    quiet: yes

- name: test if httpd_locations is set correctly
  assert:
    that:
      - httpd_locations is iterable
    quiet: yes
  when:
    - httpd_locations is defined

- name: test if item in httpd_locations is set correctly
  assert:
    that:
      - item.name is defined
      - item.location is defined
      - item.backend_url is defined
    quiet: yes
  loop: "{{ httpd_locations }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - httpd_locations is defined

- name: test if httpd_vhosts is set correctly
  assert:
    that:
      - httpd_vhosts is iterable
    quiet: yes
  when:
    - httpd_vhosts is defined

- name: test if item in httpd_vhosts is set correctly
  assert:
    that:
      - item.name is defined
      - item.servername is defined
    quiet: yes
  loop: "{{ httpd_vhosts }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - httpd_vhosts is defined
