---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check if ports are open
      wait_for:
        port: "{{ item }}"
        timeout: 2
      loop:
        - "8080"
        - "8443"

    - name: interact with webserver
      uri:
        url: "https://127.0.0.1:8443/mylocation1/"
        status_code: 
          - 404
          - 500
          - 502
          - 503
        validate_certs: no

    - name: see if TRACE option returns 405
      uri:
        url: "https://127.0.0.1:8443/"
        method: TRACE
        status_code:
          - 405
        validate_certs: no
